import { Dictionary } from "./Interface";

export const ImagePath : Dictionary<string> = {
    'jogja-header.png':'/assets/list_page/jogja-header.png',
    'ornament.png':'/assets/list_page/ornament.png',
    'wayang-gunungan.png':'/assets/list_page/wayang-gunungan.png',
    'frame.png': '/assets/home/frame.png',
    'frame_without_shadow.png': '/assets/home/frame_without_shadow.png',
    'shadow.png': '/assets/home/shadow.png',
    'gunung.png': '/assets/home/gunung.png',
    'keraton.png': '/assets/home/keraton.png',
    'malioboro.png': '/assets/home/malioboro.png',
    'pantai.png': '/assets/home/pantai.png',
    'pohon_kecil.png': '/assets/home/pohon_kecil.png',
    'tugu.png': '/assets/home/tugu.png',
    'accomodation.png': '/assets/places_to_go/accomodation.png',
    'cuisine.png': '/assets/places_to_go/cuisine.png',
    'cultures.jpg': '/assets/places_to_go/cultures.jpg',
    'landmarks.png': '/assets/places_to_go/landmarks.png',
    'nature.jpg': '/assets/places_to_go/nature.jpg',
    'hanoman.jpg': '/assets/budgetin_page/hanoman.jpg',
    'pattern_diamond.png': '/assets/footer/pattern_diamond.png',
    'pattern_floral.png': '/assets/footer/pattern_floral.png',
    'pattern_parang.png': '/assets/footer/pattern_parang.png',
    'tunas1.png': '/assets/footer/tunas1.png',
    'Hotels.png': '/assets/budgetin/Hotels.png',
    'Restaurants.png': '/assets/budgetin/Restaurants.png',
    'Tourism Spots.png': '/assets/budgetin/Tourism Spots.png',
    'angkringan.png': '/assets/budgetin/header/angkringan.png',
    'becak.png': '/assets/budgetin/header/becak.png',
    'kursi.png': '/assets/budgetin/header/kursi.png',
    'pohon_besar.png': '/assets/budgetin/header/pohon_besar.png',
}